name: Update IAM Roles

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci

      - run: |
          git config user.email "patrick.dougherty.0208@gmail.com"
          git config user.name "(Workflow) Patrick Dougherty"
          npm version patch

      - name: Regenerate Roles
        run: npm run save-roles
        env:
          API_KEY: ${{ secrets.GCP_KEY }}

      - name: Check if new roles
        id: git_diff
        run: |
          if git diff --quiet src/google/data/roles.json; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, committing and pushing"
            git config user.email "patrick.dougherty.0208@gmail.com"
            git config user.name "(Workflow) Patrick Dougherty"
            git add src/google/data/roles.json
            git commit --amend --no-edit
            git push
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.git_diff.outputs.changes == 'true'
        uses: softprops/action-gh-release@v1

      - name: Publish
        if: steps.git_diff.outputs.changes == 'true'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
